plone:
  image: eeacms/plone-copernicus-land:2016.08.05
  ports:
  - "8080:8080"
  volumes:
  - ./src:/plone/instance/src
  volumes_from:
  - plone_data
  command: ["fg"]

plone_data:
  image: busybox
  volumes:
  - /data/filestorage
  - /data/blobstorage
  command: ["chown", "-R", "500:500", "/data"]
